### ISSUE TITLE
How does this tool differ from expac?

### ISSUE THREAD

**Issue by Earnestly** [pvpscript/lspac#2]
It might be useful to note the differences/comparison between this and `expac` or other tools like `pacinfo` in the README.

**Comment by pvpscript** [comment]
The main difference between `pacinfo` is that, in `pacinfo` you cannot control the output format, so it's not very parsing friendly when creating scripts with it. And about `expac`, I didn't knew about it, and as it turns out they do pretty much the same thing, except that `expac` is way more clever when it comes to controlling the output because it uses percentage formatting, while `lspac` outputs are selected the same way they are in a tool called `lsblk`, which was one of the inspirations for creating `lspac`.
